spring:
 profiles:
  active:
   - dev
---

spring:
 profiles: dev
 application:
  name: microservicecloud-config-atguigu-dev
  
---
 profiles: test
  application:
  name: microservicecloud-config-atguigu-test
